CREATE SCHEMA public;

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    login VARCHAR(80) NOT NULL,
    email VARCHAR(80) NOT NULL,
    birthday TIMESTAMP NULL,
    PRIMARY KEY (id),
    CONSTRAINT u0_users_login UNIQUE (login)
);

CREATE TABLE role (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    name VARCHAR(80) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT r0_role_name UNIQUE (name)
);

CREATE TABLE user_role (
    id_user BIGINT NOT NULL,
    id_role BIGINT NOT NULL,
    PRIMARY KEY (id_user, id_role),
    CONSTRAINT fk0_user FOREIGN KEY (id_user) REFERENCES users (id),
    CONSTRAINT fk0_role FOREIGN KEY (id_role) REFERENCES role (id)
);
